fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
#           - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/', stop: true }
    zone:
        - { path: ^/api/* }
    body_listener:
        enabled: true
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException' : true
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': true
        codes:
            'Symfony\Component\Security\Core\Exception\BadCredentialsException': 401
    allowed_methods_listener: true
#        enabled: true
#        exception_controller: 'fos_rest.exception.controller:showAction'
